affixes = [["SS","Same Subject","ngapak"],
["SUBJ","Subjunctive","ngapak"],
["ORI","Orientative Marker","pakman"],
["ABL","Ablative","manta"],
["TERM","Terminative","kaman"],
["SS","Same Subject","ngapa"],
["DS","Different Subject","kpika"],
["SUBJ","Subjunctive","ngapa"],
["COND","Conditional","kpika"],
["POST","Postessive Marker","waʃa"],
["DUB","Non-Evidentual Dubitative Marker","ʧaɾi"],
["DUB","Non-Evidentual Dubitative Marker","ʒaɾi"],
["TOT","Totality Marker","ʒata"],
["SEMB","Semblative Marker","ʃina"],
["FUT(imd)","Immediate Future","gɾin"],
["PL","Plural Marker","kuna"],
["COM","Commitative Marker","ndin"],
["RECP","Reciprocal Marker","naxu"],
["RECP","Reciprocal Marker","naku"],
["AFF(cert)","Emphatic Affirmation of Certainty","maɾi"],
["DS","Different Subject","pika"],
["COND","Conditional","pika"],
["SUPER","Supersessive","hawa"],
["DUB","Non-Evidentual Dubitative Marker","jaɾi"],
["INTRA","Intrative Marker","puɾa"],
["DEP","Despreciative Marker","ʐuku"],
["AUG","Augmentative Marker","sapa"],
["AUG","Augmentative Marker","puɾa"],
["DES","Desiderative Marker","naja"],
["EXA","Exageration Marker","siki"],
["FUT","Future","ʃun"],
["PAST_PART","Past Participle Marker","ʃka"],
["PROG_PART","Same Subject Gerund/Converb","ʃpa"],
["SS","Same Subject","ʧun"],
["SUBJ","Subjunctive","ʧun"],
["CONJ","Conjunction","piʃ"],
["CONJ","Conjunction","paʃ"],
["PAST","Past","ʐka"],
["FUT","Future","nga"],
["IMP(formal)","Formal Imparative Marker","pai"],
["INTER(wh)","Wh Question Marker","tak"],
["DET","Determiner","ese"],
["INST","Instrumental Marker","wan"],
["COM","Commitative Marker","wan"],
["DIR","Directional Marker","man"],
["GEN","Genitive Marker","pak"],
["BEN","Benefactive Marker","pak"],
["POSS","Possessive Marker","juk"],
["FUT","Future","ʃa"],
["NEG","Negative Marker","ʧu"],
["INTER(echo)","Echo Question Marker","ʧu"],
["EXCL","Exclusive Marker","ʒa"],
["INFER","Inferred Information Marker","ʃi"],
["DUB","Non-Evidentual Dubitative Marker","ʧa"],
["CAU","Causative Marker","ʧi"],
["INF","Infinitive Marker","na"],
["PROG","Progressive/Continous Marker","xu"],
["PROG","Progressive/Continous Marker","ku"],
["TOP","Topic Marker","ka"],
["ACC","Accusitive Marker","ta"],
["VAL","Validative Marker","mi"],
["REFL","Reflexive Marker","ʐi"],
["1DO","First Person Direct Object Pronoun Marker","wa"],
["INTER(wh)","Wh Question Marker","ta"],
["LOC","Locative Marker","pi"],
["GEN","Genitive Marker","pa"],
["DIM","Diminutive Marker","ku"],
["DIM","Diminutive Marker","wa"],
["DIM","Diminutive Marker","su"],
["TRANS","Translocative Marker","mu"],
["VERB","Verbalization","ja"],
["DIM","Diminutive Marker","k"],
["PRES","Present","n"],
["IMP","Imparative Marker","j"],
["s","Singular","Ø"],
["F","Feminine (Spanish derived)","a"],
["M","Masculine (Spanish derived)","o"],
["NOM","Nominal Marker","j"],
["AG","Agentive Marker","k"]]
