affixes= [["SS","Same Subject","ngapak"],
["SUBJ","Subjunctive","ngapak"],
["ORI","Orientative Marker","pakman"],
["ABL","Ablative","manta"],
["POST","Postessive Marker","washa"],
["TERM","Terminative","kaman"],
["SS","Same Subject","ngapa"],
["DS","Different Subject","kpika"],
["SUBJ","Subjunctive","ngapa"],
["COND","Conditional","kpika"],
["DUB","Non-Evidentual Dubitative Marker","chari"],
["DUB","Non-Evidentual Dubitative Marker","llari"],
["TOT","Totality Marker","llata"],
["SEMB","Semblative Marker","shina"],
["FUT","Future","shun"],
["FUT(imd)","Immediate Future","grin"],
["PL","Plural Marker","kuna"],
["PAST_PART","Past Participle Marker","shka"],
["COM","Commitative Marker","ntin"],
["RECP","Reciprocal Marker","nahu"],
["RECP","Reciprocal Marker","naku"],
["AFF(cert)","Emphatic Affirmation of Certainty","mari"],
["PROG_PART","Same Subject Gerund/Converb","shpa"],
["SS","Same Subject","chun"],
["DS","Different Subject","pika"],
["SUBJ","Subjunctive","chun"],
["COND","Conditional","pika"],
["CONJ","Conjunction","pish"],
["CONJ","Conjunction","pash"],
["SUPER","Supersessive","hawa"],
["DUB","Non-Evidentual Dubitative Marker","yari"],
["INTRA","Intrative Marker","pura"],
["DEP","Despreciative Marker","ruku"],
["AUG","Augmentative Marker","sapa"],
["AUG","Augmentative Marker","pura"],
["DES","Desiderative Marker","naya"],
["EXA","Exageration Marker","siki"],
["PAST","Past","rka"],
["FUT","Future","sha"],
["FUT","Future","nga"],
["IMP(formal)","Formal Imparative Marker","pay"],
["NEG","Negative Marker","chu"],
["INTER(wh)","Wh Question Marker","tak"],
["INTER(echo)","Echo Question Marker","chu"],
["DET","Determiner","ese"],
["INST","Instrumental Marker","wan"],
["COM","Commitative Marker","wan"],
["DIR","Directional Marker","man"],
["GEN","Genitive Marker","pak"],
["EXCL","Exclusive Marker","lla"],
["INFER","Inferred Information Marker","shi"],
["DUB","Non-Evidentual Dubitative Marker","cha"],
["CAU","Causative Marker","chi"],
["BEN","Benefactive Marker","pak"],
["POSS","Possessive Marker","yuk"],
["INF","Infinitive Marker","na"],
["PROG","Progressive/Continous Marker","hu"],
["PROG","Progressive/Continous Marker","ku"],
["TOP","Topic Marker","ka"],
["ACC","Accusitive Marker","ta"],
["VAL","Validative Marker","mi"],
["REFL","Reflexive Marker","ri"],
["1DO","First Person Direct Object Pronoun Marker","wa"],
["INTER(wh)","Wh Question Marker","ta"],
["LOC","Locative Marker","pi"],
["GEN","Genitive Marker","pa"],
["DIM","Diminutive Marker","qu"],
["DIM","Diminutive Marker","ku"],
["DIM","Diminutive Marker","wa"],
["DIM","Diminutive Marker","su"],
["TRANS","Translocative Marker","mu"],
["VERB","Verbalization","ya"],
["PRES","Present","n"],
["IMP","Imparative Marker","y"],
["s","Singular","Ø"],
["F","Feminine (Spanish derived)","a"],
["M","Masculine (Spanish derived)","o"],
["NOM","Nominal Marker","y"],
["AG","Agentive Marker","k"]];
